on:
  workflow_call:
    inputs:
      image_repo_project:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      environment:
        required: true
        type: string
      build_args:
        required: false
        default: 'None'
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    outputs:
      image_repo:
        description: "The image repo"
        value: ${{ jobs.build_and_push.outputs.image_repo }}
      image_tag:
        description: "The image tag"
        value: ${{ jobs.build_and_push.outputs.image_tag }}
      image:
        description: "The image full path"
        value: ${{ jobs.build_and_push.outputs.image }}

jobs:
  build_and_push:
    name: Build_and_Push
    runs-on: ubuntu-latest
    outputs:
      image_repo: ${{ steps.repo.outputs.repo }}
      image_tag: ${{ steps.tag.outputs.image_tag }}
      image: ${{ steps.image.outputs.image }}
    steps:
      - name: Configure AWS credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: 'no'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image tag
        id: tag
        shell: bash
        run: |
          if [[ ${{ inputs.environment }} == "dev" ]];then
          echo "image_tag=$(date +'%y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          else
          echo "image_tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Set image repo
        id: repo
        shell: bash
        run: |
          echo "repo=${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_repo_project }}" >> $GITHUB_OUTPUT

      - name: Set image
        id: image
        run: |
          echo "image=${{ steps.repo.outputs.repo }}:${{ steps.tag.outputs.image_tag }}" >> $GITHUB_OUTPUT

      - name: Show variables
        run: echo ${{ github.ref }} ${{ steps.login-ecr.outputs.registry }} ${{ steps.tag.outputs.image_tag }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        if: ${{ inputs.build_args == 'None' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.image }}

      - name: Build with args and push
        if: ${{ inputs.build_args != 'None' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            ${{ inputs.build_args }}
          push: true
          tags: ${{ steps.image.outputs.image }}
